final_submission/website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, abort, redirect, url_for, session
from flask_login import login_required, current_user
from .models import Note, Product, Cart, Payment, CreditCard, Smartphone
from . import db
import json
import stripe


views = Blueprint('views', __name__)

    # if request.method == 'POST': 
    #     note = request.form.get('note')#Gets the note from the HTML 

    #     if len(note) < 1:
    #         flash('Note is too short!', category='error') 
    #     else:
    #         new_note = Note(data=note, user_id=current_user.id)  #providing the schema for the note 
    #         db.session.add(new_note) #adding the note to the database 
    #         db.session.commit()
    #         flash('Note added!', category='success')

    # return render_template("home.html", user=current_user)

@views.route('/')
@login_required
def home():
    products = Product.query.all()
    return render_template('new.html', products = products, user = current_user)


@views.route('/smartphones')
@login_required
def smartphones():
    smartphones = Smartphone.query.all()
    return render_template('smartphones.html', smartphones = smartphones, user = current_user)


@views.route('/smartphone_detail/<int:id>')
def smartphone_detail(id):
    smartphone = Smartphone.query.get(id)
    return render_template('smartphone_detail.html', smartphone=smartphone, user = current_user)


@views.route('/product/<int:id>')
@login_required
def product_detail(id):
    # Query the Product table for the product with the specified id
    product = Product.query.get(id)
    
    # If no product was found with that id, return a 404 error
    if not product:
        abort(404)
    if product.id<70:
        smartphone = Smartphone.query.get(product.id)
        return render_template('smartphone_detail.html', user=current_user, smartphone = smartphone)
    # Render the product detail template with the product and the current user
    else:
        return 'dengindi'

@views.route('/cart')
def cart():
    # Get the user's cart from the database
    user_id = current_user.id
    cart = Cart.query.filter_by(user_id=user_id).first()
    
    # If the user has no items in their cart, display a message
    if not cart or not cart.product_list:
        # return render_template('cart.html', message='Your cart is empty.', user = current_user)
        return render_template('no_cart.html', user_id = user_id, cart = cart, user = current_user)
    
    # print(cart.product_list[0])
    # Split the product IDs and quantities into lists
    if cart.product_list!='':
        product_ids = [int(x) for x in cart.product_list.split(',')]
    else:
        product_ids = []
    # print(product_ids)
    if cart.quantity_list!='':
        quantities = [int(x) for x in cart.quantity_list.split(',')]
    else:
        quantities = []
    # print(quantities)
    
    # Get the product objects for each ID
    products = []
    for product_id in product_ids:
        product = Product.query.get(product_id)
        # print(product.price)
        if product:
            products.append(product)
    product_quantities = []
    # Zip the products and quantities together for display
    # product_quantities = zip(products, quantities)
    print(products)  
    print(quantities)

    total = 0  
    for i in range(0, len(quantities)):
        if (products[i].price  == None):
            products[i].price = 10000

        total = total+ quantities[i]*products[i].price
        product_quantities.append([products[i], quantities[i]])

    return render_template('cart.html', products = products, quantities = quantities, user = current_user, product_quantities = product_quantities, total = total)
    # return render_template('cart.html', product_quantities=product_quantities, total_price=total_price, user = current_user)



@views.route('/add-to-cart', methods=['POST'])
def add_to_cart():
    # Get the product ID from the form data
    product_id = request.form.get('product_id')
    quantity = int(request.form.get('quantity'))
    # Get the user's cart from the database
    user_id = current_user.id
    cart = Cart.query.filter_by(user_id=user_id).first()
    print('hello')
    if not cart:
        print("gudda")
        cart = Cart(user_id=user_id, product_list='', quantity_list='')
    if (cart.product_list!='') and (cart.product_list[0]==','):
        cart.product_list = cart.product_list[1:]
        cart.quantity_list = cart.quantity_list[1:]
    print('print()cart.product_list')
    print(cart.product_list)
    if cart.product_list!='':
        product_ids = [int(x) for x in cart.product_list.split(',')]
    else:
        product_ids = []
    # print(product_ids)
    if cart.quantity_list!='':
        quantities = [int(x) for x in cart.quantity_list.split(',')]
    else:
        quantities = []
    # print(quantities)
    
    # If the product is already in the cart, increase the quantity by 1
    print(product_ids)
    print(quantities)
    print(product_id)
    # bool = True
    # for k in range (0, len(product_ids)):
    #     print(product_ids[k] == product_id)
    #     if product_ids[k] == product_id:
    #         quantities[k] += quantity
    #         bool = False
    #         break
    # cart.quantity_list = ','.join(str(q) for q in quantities)
    # print(bool)
    # if bool:
    #     cart.product_list += f',{product_id}'
    #     cart.quantity_list += f',{quantity}'

    if product_id in product_ids:
        product_index = product_ids.index(int(product_id))
        print(product_index)
        quantities[product_index] += quantity
        cart.quantity_list = ','.join(str(q) for q in quantities)
        
    else:
        if cart.product_list=='':
            cart.product_list += f'{product_id}'
            cart.quantity_list += f'{quantity}'
        else:
            cart.product_list += f',{product_id}'
            cart.quantity_list += f',{quantity}'


    # Save the cart to the database
    db.session.add(cart)
    db.session.commit()
    
    # Redirect the user back to the cart page
    return redirect(url_for('views.cart'))

# @views.route('/delete-note', methods=['POST'])
# def delete_note():  
#     note = json.loads(request.data) # this function expects a JSON from the INDEX.js file 
#     noteId = note['noteId']
#     note = Note.query.get(noteId)
#     if note:
#         if note.user_id == current_user.id:
#             db.session.delete(note)
#             db.session.commit()

#     return jsonify({})



@views.route("/payment", methods=["GET", "POST"])
@login_required
def payment():
    if request.method == "POST":
        # get the payment details from the form
        payment_method = request.form.get("payment-method")
        card_number = request.form.get("card-number")
        expiry_date = request.form.get("expiry-date")
        cvv = request.form.get("cvv")
        name_on_card = request.form.get("Name as on card")

        # look up the user's credit card by card number
        credit_card = CreditCard.query.filter_by(card_number=card_number, user_id=current_user.id).first()

        # check if credit card is valid
        if not credit_card or credit_card.expiry_date != expiry_date or credit_card.cvv != cvv or credit_card.name_on_card != name_on_card:
            return render_template("payment_failure.html")

        # create a new payment object
        payment = stripe.PaymentIntent.create(
            amount=1000, # set the payment amount in cents
            currency="usd",
            payment_method_types=[payment_method],
            payment_method_data={
                payment_method: {
                    "card": {
                        "number": card_number,
                        "exp_month": int(expiry_date.split("/")[0]),
                        "exp_year": int(expiry_date.split("/")[1]),
                        "cvc": cvv,
                        "name": name_on_card,
                    }
                }
            },
        )

        # check the payment status
        if payment.status == "succeeded":
            # create a new Payment record in the database
            new_payment = Payment(user_id=current_user.id, amount=1000, status="succeeded")
            db.session.add(new_payment)
            db.session.commit()
            return render_template("payment_success.html", payment_id=payment.id)
        else:
            return render_template("payment_failure.html")

    # render the payment page template
    return render_template("payment.html", user=current_user)

final_submission/website/templates/cart.html
{% extends 'base.html' %}

{% block title %}Cart{% endblock %}

{% block content %}
  <div class="container my-5">
    <h1 class="mb-4">Shopping Cart</h1>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Product</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col">Total</th>
        </tr>
      </thead>
      <tbody>
        {% for product_quantity in product_quantities %}
        <tr>
          <td>
            <div class="media">
              <a href="{{ url_for('views.product_detail', id=product_quantity[0].id) }}">
                <img src="{{ url_for('static', filename='images/smartphones/' + product_quantity[0].url) }}" class="mr-3" alt="{{ product_quantity[0].name }}" style="width: 100px; height: 100px;">
              </a>
              <div class="media-body">
                <h5 class="mt-0 mb-1">{{ product_quantity[0].name }}</h5>
                <p class="mb-0">{{ product_quantity[0].description }}</p>
              </div>
            </div>
          </td>
          <td>Rs.{{ product_quantity[0].price }}</td>
          <td>{{ product_quantity[1] }}</td>
          <td>Rs.{{ product_quantity[0].price * product_quantity[1] }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="row">
      <div class="col-md-4 offset-md-8">
        <table class="table table-borderless">
          <tbody>
            <tr>
              <th>Total:</th>
              <td>Rs.{{ total }}</td>
            </tr>
          </tbody>
        </table>
        <a href="{{ url_for('views.home') }}" class="btn btn-secondary mr-2">Continue Shopping</a>
        <a href="{{ url_for('views.payment') }}" class="btn btn-primary">Buy Now</a>
      </div>
    </div>
  </div>
{% endblock %}

final_submission/website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<!-- <h1 align="center">Notes</h1>
<ul class="list-group list-group-flush" id="notes">
  {% for note in user.notes %}
  <li class="list-group-item">
    {{ note.data }}
    <button type="button" class="close" onClick="deleteNote({{ note.id }})">
      <span aria-hidden="true">&times;</span>
    </button>
  </li>
  {% endfor %}
</ul>
<form method="POST">
  <textarea name="note" id="note" class="form-control"></textarea>
  <br />
  <div align="center">
    <button type="submit" class="btn btn-primary">Add Note</button>
  </div>
</form> -->
{% endblock %}

final_submission/website/templates/new.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/counter.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.min.css') }}">
    <link  rel="stylesheet" href="{{ url_for('static', filename='css/owl.theme.default.min.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='new.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/text_on_image.css') }}">

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-white text-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link text-dark link" href="/">Home</a>
          <a class="nav-item nav-link text-dark link" href="/logout">Logout</a>
          <a class="nav-item nav-link text-dark link" href="/cart">Cart</a>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Products
            </button>
            <div class="dropdown-menu " aria-labelledby="Products">
              <a class="dropdown-item" href="/smartphones">Smart Phones</a>
            </div>
          </div>
          {% else %}
          <a class="nav-item nav-link text-dark link"   href="/login">Login</a>
          <a class="nav-item nav-link text-dark link"   href="/sign-up">Sign Up</a>
          
          {% endif %}
        </div>
      </div>
  
    </nav>
    <div class="bd-example">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <!-- <img src="{{ url_for('static', filename='images/1.png') }}" class="d-block w-100" alt="..."> -->
              <img src="{{ url_for('static', filename='images/headphone.jpeg') }}" class="d-block w-100" id="first_image" alt="...">

              <div class="carousel-caption d-none d-md-block">
               <p class="slider-title">Your complete electronic store</p>
               <!-- <p class="slider-text">All brands availav\</p> -->
               <!-- <p class="buttob mt-5"> <a class="btn btn-lg btn-success">BUY NOW</a>&nbsp; &nbsp; <a class="btn btn-danger btn-lg">KNOW MORE</a></p>  -->
              </div>
            </div>
            <div class="carousel-item">
              <img src="{{ url_for('static', filename='images/intro_laptop.jpeg') }}" class="d-block w-100" id="second_image" alt="...">
              <div class="carousel-caption d-none d-md-block">
                <p class="slider-title">EMI Available In <i class="fa fa-credit-card-alt" aria-hidden="true"></i></p>
               <!-- <p class="slider-text">50% off in some popular brand product.</p> -->
               <!-- <p class="buttob mt-5"> <a class="btn btn-lg btn-success">BUY NOW</a>&nbsp; &nbsp; <a class="btn btn-danger btn-lg">KNOW MORE</a></p>  -->
              </div>
            </div>

            <!-- <div class="carousel-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                  <p class="slider-title">thopu products <i class="fa fa-credit-card-alt" aria-hidden="true"></i></p>
                 <p class="slider-text">50% off in some popular brand product.</p>
                 <p class="buttob mt-5"> <a class="btn btn-lg btn-success">BUY NOW</a>&nbsp; &nbsp; <a class="btn btn-danger btn-lg">KNOW MORE</a></p> 
                </div>
              </div> -->
            
          </div>
          <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
<!-- slider end -->

<!-- sliding sta -->
<div class="container">
    <div class="row mt-5 mb-5">
        <div class="col-md-12">
            <h1 class="text-center">Best selling earphones</h1>
        </div>
    </div>
</div>


<div class="col-md-4">
  <div class="card mb-4 shadow-sm" style="height: 100%;">
    <div style="height: 0; padding-bottom: 100%; position: relative;">
      <img class="card-img-top" src="{{ url_for('static', filename='images/smartphones/' + '5.jpeg') }}" alt="" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;">
    </div>
    <div class="card-body">
      <h5 class="card-title"></h5>
    
      <p class="card-text"></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <a href="{{ url_for('views.smartphone_detail', id=5) }}" class="btn btn-sm btn-outline-primary">View</a>
          <a href="#" class="btn btn-sm btn-outline-secondary">Add to Cart</a>
        </div>
        <small class="text-muted"></small>
      </div>
    </div>
  </div>
</div>


<div class="col-md-4">
  <div class="card mb-4 shadow-sm" style="height: 100%;">
    <div style="height: 0; padding-bottom: 100%; position: relative;">
      <img class="card-img-top" src="{{ url_for('static', filename='images/smartphones/' + '6.jpeg') }}" alt="" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;">
    </div>
    <div class="card-body">
      <h5 class="card-title"></h5>
    
      <p class="card-text"></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <a href="{{ url_for('views.smartphone_detail', id=5) }}" class="btn btn-sm btn-outline-primary">View</a>
          <a href="#" class="btn btn-sm btn-outline-secondary">Add to Cart</a>
        </div>
        <small class="text-muted"></small>
      </div>
    </div>
  </div>
</div>

<div class="col-md-4">
  <div class="card mb-4 shadow-sm" style="height: 100%;">
    <div style="height: 0; padding-bottom: 100%; position: relative;">
      <img class="card-img-top" src="{{ url_for('static', filename='images/smartphones/' + '7.jpeg') }}" alt="" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;">
    </div>
    <div class="card-body">
      <h5 class="card-title"></h5>
    
      <p class="card-text"></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <a href="{{ url_for('views.smartphone_detail', id=5) }}" class="btn btn-sm btn-outline-primary">View</a>
          <a href="#" class="btn btn-sm btn-outline-secondary">Add to Cart</a>
        </div>
        <small class="text-muted"></small>
      </div>
    </div>
  </div>
</div>

<div class="col-md-4">
  <div class="card mb-4 shadow-sm" style="height: 100%;">
    <div style="height: 0; padding-bottom: 100%; position: relative;">
      <img class="card-img-top" src="{{ url_for('static', filename='images/smartphones/' + '8.jpeg') }}" alt="" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;">
    </div>
    <div class="card-body">
      <h5 class="card-title"></h5>
    
      <p class="card-text"></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <a href="{{ url_for('views.smartphone_detail', id=5) }}" class="btn btn-sm btn-outline-primary">View</a>
          <a href="#" class="btn btn-sm btn-outline-secondary">Add to Cart</a>
        </div>
        <small class="text-muted"></small>
      </div>
    </div>
  </div>
</div>







<!-- sliding end -->

<!-- effect start -->


  <div class="container-fluid">
    <div class="row">
      <div class="col-12 p-0">
        <img src="{{ url_for('static', filename='images/cute_boy.jpeg') }}" class="img-fluid">
        <div class="text-on-image">
        </div>
          <h1>Follow us on: instagram(@deodio)</h1>
          <p></p>
        
      </div>
    </div>
  </div>

<!-- effect end -->


<!-- contact us end  -->


    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script src="js/counter.js"></script>
    <script src="{{ url_for('static', filename='css/counter.js') }}"></script>
    <script src="{{ url_for('static', filename='css/owl.carousel.min.js') }}"></script>
    <script src="js/owl.carousel.min.js"></script>
   <script>
	  
	$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:3,
            nav:false
        },
        1000:{
            items:4,
            nav:false,
            loop:false
        }
    }
})  
   </script>

<!-- {% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
  fetch("/delete-note", {
    method: "POST",
    body: JSON.stringify({ noteId: noteId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %} -->
  </body>
</html>

final_submission/website/templates/no_cart.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <h1>Cart</h1>
    {% if cart and cart.product_list %}
      {% for product, quantity in product_quantities %}
        <p>{{ product.name }} - Quantity: {{ quantity }}</p>
      {% endfor %}
      <p>Total: {{ total }}</p>
    {% else %}
      <p>Your cart is empty.</p>
    {% endif %}
    <a href="{{ url_for('views.home') }}">Continue shopping</a>

 {% endblock %}

final_submission/website/templates/product_detail.html
<!-- o modify the "product_detail" page to allow the user to add a product with a specified quantity: -->

{% extends 'base.html' %}

{% block title %}{{ product.name }} - Product Details{% endblock %}

{% block content %}
  <div class="container my-5">
    <div class="row">
      <div class="col-md-6">
        <img src="{{ url_for('static', filename='images/' + product.url) }}" class="img-fluid" alt="{{ product.name }}">
      </div>
      <div class="col-md-6">
        <h1 class="mb-4">{{ product.name }}</h1>
        <p>{{ product.description }}</p>
        <h2 class="mb-4">Rs.{{ product.price }}</h2>
        <form method="POST" action="{{ url_for('views.add_to_cart') }}">
          <input type="hidden" name="product_id" value="{{ product.id }}">
          <label for="quantity">Quantity:</label>
          <input type="number" name="quantity" id="quantity" value="1">
          <button type="submit" class="btn btn-primary">Add to Cart</button>
        </form>
        
      </div>
    </div>
  </div>
{% endblock %}

final_submission/website/templates/products.html
{% extends 'base.html' %}

{% block title %}Products{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      {% for product in products %}
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm" style="height: 100%;">
          <div style="height: 0; padding-bottom: 100%; position: relative;">
            <img class="card-img-top" src="{{ url_for('static', filename='images/' + product.url) }}" alt="" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;">
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{{ url_for('views.product_detail', id=product.id) }}" class="btn btn-sm btn-outline-primary">View</a>
                <a href="#" class="btn btn-sm btn-outline-secondary">Add to Cart</a>
              </div>
              <small class="text-muted">${{ product.price }}</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

final_submission/website/templates/smartphone_detail.html
{% extends 'base.html' %}

{% block title %}{{ smartphone.brand_name }} {{ smartphone.model_name }}{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <img src="{{ url_for('static', filename='images/smartphones/' + smartphone.url) }}" class="img-fluid" alt="">
      </div>
      <div class="col-md-6">
        <h1 class="mt-5">{{ smartphone.brand_name }} {{ smartphone.model_name }}</h1>
        <!-- <h3 class="mt-3">${{ smartphone.lowestprice }}</h3> -->
        <hr>
      </div>
    </div>
    <div class="card-body">
      <h5 class="card-title">{{ smartphone.brand_name }} {{ smartphone.model_name }}</h5>
      <p class="card-text">{{ smartphone.description }}</p>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">OS: {{ smartphone.os }}</li>
        <li class="list-group-item">Screen Size: {{ smartphone.screen_size }}</li>
        <li class="list-group-item">Memory Size: {{ smartphone.memory_size }}</li>
        <li class="list-group-item">Battery Size: {{ smartphone.battery_size }}</li>
        <li class="list-group-item">Price: {{ smartphone.lowest_price }}</li>
      </ul>

      <form method="POST" action="{{ url_for('views.add_to_cart') }}">
        <input type="hidden" name="product_id" value="{{ smartphone.id }}">
        <label for="quantity">Quantity:</label>
        <input type="number" name="quantity" id="quantity" value="1">
        <button type="submit" class="btn btn-primary">Add to Cart</button>
      </form>

      <!-- <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <a href="#" class="btn btn-primary btn-lg">Add to Cart</a>
          <a href="#" class="btn btn-warning btn-lg">Buy Now</a>
        </div>
        <small class="text-muted">Rs.{{ smartphone.lowest_price }}</small>
      </div> -->
    </div>
  </div>
{% endblock %}

final_submission/website/templates/smartphones.html
{% extends 'base.html' %}

{% block title %}Smartphones{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      {% for smartphone in smartphones %}
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm" style="height: 100%;">
          <div style="height: 0; padding-bottom: 100%; position: relative;">
            <img class="card-img-top" src="{{ url_for('static', filename='images/smartphones/' + smartphone.url) }}" alt="" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;">
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ smartphone.brand_name }} {{ smartphone.model_name }}</h5>
          
            <p class="card-text">{{ smartphone.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{{ url_for('views.smartphone_detail', id=smartphone.id) }}" class="btn btn-sm btn-outline-primary">View</a>
                <a href="#" class="btn btn-sm btn-outline-secondary">Add to Cart</a>
              </div>
              <small class="text-muted">${{ smartphone.price }}</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}